language: python
sudo: required
cache: pip

install:
- pip install -e .
- pip install pycodestyle
- sudo apt-get update
- sudo apt-get install ruby
- gem install bundle
- gem install jeykll
- bundle install
# - pip install mkdocs
# - pip install pymdown-extensions
# - chmod +x ./deploy-docs.sh

matrix:
  include:
  - os: linux
    python: 2.7
  - os: linux
    python: 3.3
  - os: linux
    python: 3.4
  - os: linux
    env: BUILD_DOCS="true"
    python: 3.5
  - os: linux
    python: pypy

script:
- python setup.py test
- pycodestyle .
- (cd "samples/replicate-workbook" && python replicate_workbook.py)
- (cd "samples/list-tds-info" && python list_tds_info.py)
- (cd "samples/show-fields" && python show_fields.py)
# - bundle exec jekyll build

# after_success:
#   - bash deploy-docs.sh
