# Site information
site_name: Tableau Document API (Python)
repo_url: https://github.com/tableau/document-api-python/
copyright: © Tableau Software

# Pages and Layout
pages:
  - Intro: index.md
  - Documentation:
      - 'User Guide': user-guide.md
      - 'API Ref': api-ref.md
  - Contributing:
    - contributing.md
    - devguide.md

theme: readthedocs
extra_css:
  - css/extra.css

# Markdown Stuff
markdown_extensions:
    - admonition # Customize for 'Version Added' ?
    - pymdownx.extra # To use superfences so code and lists work nicely
